import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, CircleDollarSign, CreditCard, LogOut, Plus, Search, ShieldCheck, Users, Activity, AlertTriangle, Pencil } from "lucide-react";
import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { staggerContainer, fadeUp } from "@/lib/animations";

export const Route = createFileRoute("/platform")({ ssr: false, head: () => ({ meta: [{ title: "Prime Haven console — Mene" }, { name: "robots", content: "noindex, nofollow" }] }), component: Platform });

type Church = { id:string; name:string; subdomain:string; tier:"basic"|"standard"|"premium"; status:"active"|"grace"|"suspended"|"closed"; contact_email:string|null; contact_phone:string|null; created_at:string; members:number; staff:number; period_end:string|null; auto_renew:boolean|null; last_payment_status:string|null; last_payment_at:string|null };
type Payment = { id:string; church:string; tier:string; amount:number; currency:string; status:string; channel:string|null; created_at:string; paid_at:string|null };
type Audit = { id:string; action:string; tenant_id:string|null; church:string|null; detail:unknown; created_at:string };
type Overview = { tenants:number; active_tenants:number; grace_tenants:number; suspended_tenants:number; members:number; attendance_30d:number; by_tier:Record<string,number>; revenue_usd_90d:number; payments_30d:number; failed_payments_30d:number; churches:Church[]; recent_payments:Payment[]; audit:Audit[] };
type Form = { id?:string; name:string; subdomain:string; tier:Church["tier"]; status:Church["status"]; contact_email:string; contact_phone:string };
const emptyForm: Form = { name:"", subdomain:"", tier:"basic", status:"active", contact_email:"", contact_phone:"" };
const fmtDate = (value:string|null) => value ? new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value)) : "—";

function Platform() {
  const { session, loading } = useAuth(); const navigate = useNavigate(); const qc = useQueryClient();
  const [search,setSearch]=useState(""); const [tier,setTier]=useState("all"); const [status,setStatus]=useState("all"); const [form,setForm]=useState<Form|null>(null); const [selected,setSelected]=useState<Church|null>(null);
  const overview = useQuery({ queryKey:["platform-overview"], enabled:!!session, retry:false, queryFn:async()=>{ const {data,error}=await supabase.rpc("platform_overview"); if(error) throw error; return data as unknown as Overview; } });
  const save = useMutation({ mutationFn:async(value:Form)=>{ if(value.id){ const {error}=await supabase.rpc("platform_update_tenant",{p_tenant:value.id,p_name:value.name,p_subdomain:value.subdomain,p_tier:value.tier,p_status:value.status,p_contact_email:value.contact_email,p_contact_phone:value.contact_phone}); if(error) throw error; } else { const {error}=await supabase.rpc("platform_create_tenant",{p_name:value.name,p_subdomain:value.subdomain,p_tier:value.tier,p_contact_email:value.contact_email,p_contact_phone:value.contact_phone}); if(error) throw error; } }, onSuccess:()=>{toast.success(form?.id?"Church updated":"Church shell created");setForm(null);qc.invalidateQueries({queryKey:["platform-overview"]});},onError:(error)=>toast.error(error instanceof Error?error.message:"Could not save church") });
  const changeStatus=useMutation({mutationFn:async({id,next}:{id:string;next:Church["status"]})=>{const {error}=await supabase.rpc("platform_set_tenant_status",{p_tenant:id,p_status:next});if(error)throw error;},onSuccess:()=>{toast.success("Church status updated");setSelected(null);qc.invalidateQueries({queryKey:["platform-overview"]});},onError:()=>toast.error("Could not update this church")});
  const churches=useMemo(()=>overview.data?.churches.filter(c=>(tier==="all"||c.tier===tier)&&(status==="all"||c.status===status)&&`${c.name} ${c.subdomain} ${c.contact_email??""}`.toLowerCase().includes(search.toLowerCase()))??[],[overview.data,search,tier,status]);
  if(loading||overview.isLoading)return <div className="grid min-h-screen place-items-center text-sm text-muted-foreground">Loading Prime Haven console…</div>;
  if(!session||overview.error)return <div className="grid min-h-screen place-items-center px-5 text-center"><div><ShieldCheck className="mx-auto size-8 text-muted-foreground"/><h1 className="mt-4 text-xl font-bold">Prime Haven access only</h1><p className="mt-2 text-sm text-muted-foreground">This console never grants access to church member records.</p><Button asChild className="mt-5"><Link to="/auth">Sign in</Link></Button></div></div>;
  const d=overview.data!;
  const stats=[{label:"Churches",value:d.tenants,icon:Building2},{label:"Active",value:d.active_tenants,icon:Activity},{label:"Aggregate members",value:d.members,icon:Users},{label:"Attendance · 30 days",value:d.attendance_30d,icon:Activity},{label:"Revenue · 90 days",value:`$${Number(d.revenue_usd_90d).toLocaleString()}`,icon:CircleDollarSign},{label:"Failed payments",value:d.failed_payments_30d,icon:AlertTriangle}];
  return <div className="min-h-screen bg-muted/25">
    <header className="sticky top-0 z-30 border-b bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><span className="grid size-9 place-items-center rounded-xl bg-black text-white"><ShieldCheck className="size-4"/></span><div><p className="font-display text-sm font-bold">Prime Haven</p><p className="text-[10px] uppercase tracking-widest text-muted-foreground">Mene operations</p></div><Button variant="ghost" size="sm" className="ml-auto" onClick={async()=>{await supabase.auth.signOut();navigate({to:"/auth"})}}><LogOut className="size-4"/> Sign out</Button></div></header>
    <main className="mx-auto max-w-7xl space-y-7 px-4 py-7 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-eyebrow">Platform overview</p><h1 className="mt-2 font-display text-3xl font-bold">Operations console</h1><p className="mt-1 text-sm text-muted-foreground">Account operations and aggregate health only. No church database access.</p></div><Button onClick={()=>setForm({...emptyForm})}><Plus className="size-4"/> Create church shell</Button></div>
    <motion.div variants={staggerContainer} initial="hidden" animate="visible" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{stats.map(({label,value,icon:Icon})=><motion.div variants={fadeUp} key={label} className="surface p-4"><Icon className="size-4 text-primary"/><p className="mt-4 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></motion.div>)}</motion.div>
    <Tabs defaultValue="churches"><TabsList className="w-full justify-start overflow-x-auto sm:w-auto"><TabsTrigger value="churches">Churches</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="audit">Audit</TabsTrigger></TabsList>
      <TabsContent value="churches" className="space-y-4"><div className="surface grid gap-3 p-4 md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search churches" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={tier} onValueChange={setTier}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All packages</SelectItem><SelectItem value="basic">Basic</SelectItem><SelectItem value="standard">Standard</SelectItem><SelectItem value="premium">Premium</SelectItem></SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="grace">Grace</SelectItem><SelectItem value="suspended">Suspended</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select></div>
      <div className="surface divide-y overflow-hidden">{churches.map(c=><button key={c.id} onClick={()=>setSelected(c)} className="flex w-full flex-wrap items-center gap-4 p-4 text-left transition-colors hover:bg-muted/50"><div className="min-w-48 flex-1"><p className="font-semibold">{c.name}</p><p className="text-xs text-muted-foreground">/c/{c.subdomain} · created {fmtDate(c.created_at)}</p></div><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{c.members.toLocaleString()} members</p><p className="text-xs text-muted-foreground">{c.staff} staff seats used</p></div><Badge variant="secondary" className="capitalize">{c.tier}</Badge><Badge variant={c.status==="active"?"default":"outline"} className="capitalize">{c.status}</Badge></button>)}{!churches.length&&<p className="p-10 text-center text-sm text-muted-foreground">No churches match these filters.</p>}</div></TabsContent>
      <TabsContent value="payments"><div className="surface divide-y">{d.recent_payments.map(p=><div key={p.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto_auto_auto]"><div><p className="font-medium">{p.church}</p><p className="text-xs text-muted-foreground">{fmtDate(p.created_at)} · {p.channel??"Unknown channel"}</p></div><Badge variant="secondary" className="w-fit capitalize">{p.tier}</Badge><p className="font-semibold">{p.currency} {Number(p.amount).toFixed(2)}</p><Badge variant={p.status==="success"?"default":"outline"} className="w-fit capitalize">{p.status}</Badge></div>)}{!d.recent_payments.length&&<p className="p-10 text-center text-sm text-muted-foreground">No recent payments.</p>}</div></TabsContent>
      <TabsContent value="audit"><div className="surface divide-y">{d.audit.map(a=><div key={a.id} className="p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-mono text-xs font-semibold">{a.action}</p><p className="text-xs text-muted-foreground">{fmtDate(a.created_at)}</p></div><p className="mt-1 text-sm">{a.church??"Platform"}</p></div>)}{!d.audit.length&&<p className="p-10 text-center text-sm text-muted-foreground">No platform actions yet.</p>}</div></TabsContent>
    </Tabs></main>
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent>{selected&&<><DialogHeader><DialogTitle>{selected.name}</DialogTitle><DialogDescription>Account and billing health. Member-level records are intentionally unavailable.</DialogDescription></DialogHeader><div className="grid gap-3 rounded-xl bg-muted/50 p-4 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Package</span><br/><b className="capitalize">{selected.tier}</b></p><p><span className="text-muted-foreground">Status</span><br/><b className="capitalize">{selected.status}</b></p><p><span className="text-muted-foreground">Members</span><br/><b>{selected.members}</b></p><p><span className="text-muted-foreground">Staff</span><br/><b>{selected.staff}</b></p><p><span className="text-muted-foreground">Period ends</span><br/><b>{fmtDate(selected.period_end)}</b></p><p><span className="text-muted-foreground">Last payment</span><br/><b>{selected.last_payment_status??"None"}</b></p></div><DialogFooter><Button variant="outline" onClick={()=>{setForm({id:selected.id,name:selected.name,subdomain:selected.subdomain,tier:selected.tier,status:selected.status,contact_email:selected.contact_email??"",contact_phone:selected.contact_phone??""});setSelected(null)}}><Pencil className="size-4"/> Edit</Button><Button variant={selected.status==="active"?"destructive":"default"} onClick={()=>{const next=selected.status==="active"?"suspended":"active";if(window.confirm(`${next==="suspended"?"Suspend":"Restore"} ${selected.name}?`))changeStatus.mutate({id:selected.id,next})}}>{selected.status==="active"?"Suspend":"Restore"}</Button></DialogFooter></>}</DialogContent></Dialog>
    <Dialog open={!!form} onOpenChange={open=>!open&&setForm(null)}><DialogContent><DialogHeader><DialogTitle>{form?.id?"Edit church account":"Create church shell"}</DialogTitle><DialogDescription>This creates the operational account only. It does not grant Prime Haven access to church records.</DialogDescription></DialogHeader>{form&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate(form)}}><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Church name</Label><Input required minLength={2} maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="space-y-2"><Label>Subdomain</Label><Input required pattern="[a-z0-9][a-z0-9-]{1,38}[a-z0-9]" value={form.subdomain} onChange={e=>setForm({...form,subdomain:e.target.value.toLowerCase()})}/></div><div className="space-y-2"><Label>Package</Label><Select value={form.tier} onValueChange={value=>setForm({...form,tier:value as Form["tier"]})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="basic">Basic</SelectItem><SelectItem value="standard">Standard</SelectItem><SelectItem value="premium">Premium</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Contact email</Label><Input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></div><div className="space-y-2"><Label>Contact phone</Label><Input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div>{form.id&&<div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={value=>setForm({...form,status:value as Form["status"]})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="grace">Grace</SelectItem><SelectItem value="suspended">Suspended</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select></div>}</div><DialogFooter><Button type="button" variant="outline" onClick={()=>setForm(null)}>Cancel</Button><Button type="submit" disabled={save.isPending}>{save.isPending?"Saving…":"Save church"}</Button></DialogFooter></form>}</DialogContent></Dialog>
  </div>;
}